[package]
name = "example-registration"
version = "0.1.0"
edition = "2021"
default-run = "example-registration"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctor = "0.2.6"
